use_frameworks!

platform :ios, '9.0'

target 'JNetworking_Example' do
  pod 'JNetworking', :path => '../'

  target 'JNetworking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
